name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v1
    - name: Update submodules
      run: |
          git submodule init
          git submodule update
    - name: Install dependencies
      run: |
        sudo apt-get install libjansson-dev
        sudo apt-get install hdf5-dev
        sudo apt-get install python3-dev
        sudo apt-get install python3-numpy
        sudo apt-get install python3-yaml
        sudo apt-get install python3-psycopg2
        sudo apt-get install swig3.0
        sudo apt-get install doxygen
    - name: configure
      run: |
        mkdir build
        cd build
        cmake ..
    - name: make
      run: |
        make
    - name: make test
      run: |
        make test
