name: Cross-compile for Windows

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get docker version
      run: docker --version

    - name: Build docker image
      run: docker build -t dlite-mingw -f Dockerfile-mingw .

      # TODO:
      #   - update the image to produce a windows installer
      #   - copy the installer out of the image and deploy
