name: Static code analysis

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Update submodules
      run: |
        git submodule init
        git submodule update

    - name: Install dependencies
      run: |
        sudo apt-get install cppcheck

    - name: Run static code analysis
      run: |
        cppcheck . --language=c -q --force --error-exitcode=2
