name: Build on Windows docker container

on: [push]

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2

    - name: Build docker image
      run: docker build -t dlite-win32 -f Dockerfile-win32 .